alias gs="git status"
alias ga="git add ."
alias gc="git commit"
alias gca="git commit -a"
alias gb="git branch -v"
alias gco="git checkout"
alias gcom="git checkout master"
alias grm='git ls-files --deleted | xargs git rm'
alias gcp='git cherry-pick'
alias pull="git pull --rebase; git submodule init; git submodule update"
alias push="git push"
alias log="git log"