alias p="cd ~/Projects"
alias pt="cd ~/Projects/pt"
alias nycrb="cd ~/Projects/nycrb"
alias matchers="cd ~/Projects/rspec_on_rails_matchers"
alias webrat="cd ~/Projects/webrat"
alias wp="cd ~/Projects/weplay.com"